;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-force-normal-state
	evil-yank
	hungry-delete-backward
	hydra-multiple-cursors/ignore
	hydra-multiple-cursors/mc/add-cursor-on-click
	multiple-cursors-mode
	my-emacs-commands-launcher/body
	my-emacs-commands-launcher/nil
	y-or-n-p-insert-y
	))

(setq mc/cmds-to-run-once
      '(
	evil-mouse-drag-region
	evil-normal-state
	hydra-multiple-cursors/nil
	))
