;;; Automatically generated by ‘recentf’ on Sat May  7 22:58:12 2022.

(setq recentf-list
      '(
        "/Users/yinghuadong/.emacs.d/lisp/init-org.el"
        "/Users/yinghuadong/.emacs.d/init.el"
        "/Users/yinghuadong/Documents/Org/GTD/TODOs.org"
        "/Users/yinghuadong/Documents/Org/GTD/Schedule.org"
        "/Users/yinghuadong/Documents/Org/GTD/Projects.org"
        "/Users/yinghuadong/Documents/Org/GTD/Inbox.org"
        "/Users/yinghuadong/.emacs.d/elpa/org-roam-20220304.647/org-roam-db.el"
        "/Users/yinghuadong/Documents/Org/org-roam-directory/2022050722_总结.org"
        "/Users/yinghuadong/.emacs.d/var/bookmark-default.el"
        "/Users/yinghuadong/Documents/Org/org-roam-directory/2022031810_无人机定位.org"
        "/opt/homebrew/Cellar/emacs-mac/emacs-28.1-mac-9.0/share/emacs/28.1/lisp/subr.el.gz"
        "/Users/yinghuadong/.emacs.d/lisp/init-ui.el"
        "/Users/yinghuadong/.emacs.d/lisp/init-font.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
