;;; Automatically generated by ‘recentf’ on Mon May  9 15:15:12 2022.

(setq recentf-list
      '(
        "/Users/yinghuadong/.emacs.d/init.el"
        "/Users/yinghuadong/.emacs.d/lisp/init-packages.el"
        "/Users/yinghuadong/.emacs.d/README.md"
        "/Users/yinghuadong/.emacs.d/custom.el"
        "/Users/yinghuadong/Documents/Org/org-roam-directory/daily/2022-05-09-Mon-周报.org"
        "/Users/yinghuadong/.emacs.d/lisp/init-org.el"
        "/opt/homebrew/Cellar/emacs-mac/emacs-28.1-mac-9.0/share/emacs/28.1/etc/HELLO"
        "/opt/homebrew/Cellar/emacs-mac/emacs-28.1-mac-9.0/Emacs.app/Contents/Info.plist"
        "/Users/yinghuadong/Documents/Org/org-roam-directory/daily/2022-03-25-Fri.org"
        "/Users/yinghuadong/Documents/周报和月报/10.25_周报/10_25.tex"
        "/Users/yinghuadong/.emacs.d/var/bookmark-default.el"
        "/Users/yinghuadong/Documents/周报和月报/10.25_周报/10_25.org"
        "/Users/yinghuadong/.zshrc"
        "/Users/yinghuadong/Documents/周报和月报/10.4_月报/研一-董英华-9月份月报.tex"
        "/Users/yinghuadong/Documents/周报和月报/10.4_月报/研一-董英华-9月份月报.org"
        "/Users/yinghuadong/Documents/Org/GTD/Projects.org"
        "/Users/yinghuadong/Documents/Org/GTD/Schedule.org"
        "/Users/yinghuadong/Documents/Org/GTD/TODOs.org"
        "/Users/yinghuadong/.emacs.d/elpa/consult-20220303.1408/consult.el"
        "/Users/yinghuadong/Pictures/壁纸/动漫/二次元/072f17e432goPBr.jpg"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
